# Bienvenidos
Este **cuaderno** revisa sus *dudas*
de programación con **python**

Declaración de Listas

In [70]:
vector_a = [1.2, 2.2, 3.3, 4.4]
lista_nombres_fem = ['kath', 'andrea', 'diana']
lista_nombres_mas = ['jose', 'freddy', 'herny']
lista_vacia = []

Unir la lista de nombres femeninos con la de
masculinos:

In [71]:
lista_estudiantes = []
lista_estudiantes.append(lista_nombres_fem)
lista_estudiantes.append(lista_nombres_mas)
lista_estudiantes




[['kath', 'andrea', 'diana'], ['jose', 'freddy', 'herny']]

Deseo una lista solo con los nombres.
Voy a utilizar un lazo **for**


In [72]:
nueva_lista = []
for chica in lista_nombres_fem:
    nueva_lista.append(chica)
    
nueva_lista


['kath', 'andrea', 'diana']

In [73]:
for chico in lista_nombres_mas:
    nueva_lista.append(chico)
    
nueva_lista


['kath', 'andrea', 'diana', 'jose', 'freddy', 'herny']

In [74]:
nueva_lista_2 = lista_nombres_fem+lista_nombres_mas
nueva_lista_2



['kath', 'andrea', 'diana', 'jose', 'freddy', 'herny']

 Sumar dos arreglos de longitud $n$.
 Sea $A = <a_{1}, a_{2}, \dots, a_{n}>$ 
 Sea $B = <b_{1}, b_{2}, \dots, b_{n}>$



In [75]:
import numpy as np
n = 9
A = np.random.randint(low=0, high=n, size=n, dtype=np.int)
A

array([6, 1, 3, 4, 0, 5, 0, 6, 8])

In [76]:
B = np.random.randint(low=0, high=n, size=n, dtype=np.int)
B


array([6, 6, 2, 4, 0, 6, 8, 7, 4])

$C = A + B$

In [77]:
C = A+B
C

array([12,  7,  5,  8,  0, 11,  8, 13, 12])

Que pasa si el arreglo no es de tipo numpy?

In [78]:
a = [1, 2, 'lenin', 4]
b = [1, 2, 4, 'holamundo']
c = a+b
c



[1, 2, 'lenin', 4, 1, 2, 4, 'holamundo']

Se desea un programa que ordene los arreglos A y B
* Bubble Sort
* Insertion Sort
## Bubble Sort 
Tarea

In [79]:
## Insertion Sort

In [80]:
def insertion_sort(arreglo):
    for i in range(1, len(arreglo)):
        key = arreglo[i]
        j = i-1
        while j>=0 and arreglo[j] > key:
            arreglo[j+1] = arreglo[j]
            j-=1
        arreglo[j+1] = key
    # print(i)
    return arreglo
        

Ejecución de la función **insertion_sort()**

In [81]:
A_ordenado = insertion_sort(A)
A_ordenado

array([0, 0, 1, 3, 4, 5, 6, 6, 8])

Requiero un programa que me permita ingresar
$n$ digitos por el usuario. 
* Si el usuario
ingreso algo que no es un nùmero, repetir.

* Si el usuario ingresa un numero, continuar.

In [92]:
check = True
while check:
    try:
        num_elementos = int(input())
        check = False
    except ValueError:
        # No ingreso el valor correcto
        # num_elementos = int(input())
        print('estoy en except porque ingresaste {}'.format(num_elementos))
        check = True
    
    print(num_elementos)
    lista_num.append(x)
lista_num
    
lista_num = []
for i in range(num_elementos):
    x = int(input())

estoy en except porque ingresaste 5
5
estoy en except porque ingresaste 5
5
estoy en except porque ingresaste 5
5
estoy en except porque ingresaste 5
5
estoy en except porque ingresaste 5
5
estoy en except porque ingresaste 5
5
5


[5, 5, 54, 5, 5]